# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5fbfea27ea531baeb751d6f1fc4643035d2194e23ee051ca9e2ac49f32446ace359f7933f392cb895c694a57bf8904becbc9b432ea527f9e0dfe77fa6f1db04

test:
  secret_key_base: af89332d1ea9f9fc774742106d8cc80cd4b3b3d2018eb01b2881c1ea0cebc383e21bede79b1c0bde410ff5b7ff421ca50e319bcfe88571b6d6942acc11d62702

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
